Automated Modular Benchmarking System: AMBSBaseCalculator
AMBSBaseCalculator abstract
The VIRTUAL base class for all calculators to inherit from.
#include "ambs_base_calculator.hpp"
Public Member Functions
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Protected Member Functions
virtual void executeCB (const ros::TimerEvent &event)=0
template<typename T >
T getResolvedParam (std::string param_name)
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
Protected Attributes
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Private Attributes
ros::Timer execute_timer_
Detailed Description
The VIRTUAL base class for all calculators to inherit from.
Todo:
Add parameter container + setters/getters
Creates a standard_control_ interface of type AMBSStandardControlInterface and a threaded timer to execute calculator logic
Constructor & Destructor Documentation
AMBSBaseCalculator() [1/2]
AMBSBaseCalculator () inline
{}
~AMBSBaseCalculator()
virtual ~AMBSBaseCalculator () inline virtual
{}
AMBSBaseCalculator() [2/2]
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name) inline
Constructor.
startCalculator() MUST BE EXPLICITLY called to start the timer
Parameters
nh NodeHandle received from the nodelet manager
node_name Explicitly necessary becase all nodelets resolve ros::this_node::getName() as nodelet manager
                                                                                   :
  node_name_(node_name),
  nh_(nh)
{
  default_control_.initDefaultInterface(nh_, node_name_);
}
References AMBSBaseCalculator::default_control_, AMBSDefaultCalculatorInterface::initDefaultInterface(), AMBSBaseCalculator::nh_, and AMBSBaseCalculator::node_name_.
Member Function Documentation
executeCB()
virtual void executeCB (const ros::TimerEvent & event) protected pure virtual
Implemented in Stopwatch, CompFloatParam, DiffFloatTemporal, and DiffPoseTemporal.
Referenced by AMBSBaseCalculator::startCalculator().
getResolvedParam()
T getResolvedParam (std::string param_name) inline protected
Gets a specified parameter by resolving to the ambs/calculators namespace.
Parameters
param_name The parameter to retrieve
Template Parameters
T nh.getParam() supports ONLY STRING, INT, DOUBLE, FLOAT and BOOL or vectors thereof
example: getResolvedParam<std::vector<double>>("some_param")
{
  std::string resolved_name = "/ambs/calculators/" + node_name_ + "/" + param_name;
  T param_value;
  if(nh_.hasParam(resolved_name))
  {
    nh_.getParam(resolved_name, param_value);
  }
  else
  {
    ROS_WARN_STREAM(node_name_ << ": Could not fetch param - " << resolved_name);
  }
  return param_value;
}
References AMBSBaseCalculator::nh_, and AMBSBaseCalculator::node_name_.
startCalculator()
void startCalculator () inline protected
Starts the timer thread. MUST BE EXPLICITLY CALLED.
{
  execute_timer_ = nh_.createTimer(ros::Duration(1.0), boost::bind(&AMBSBaseCalculator::executeCB, this, _1));
}
References AMBSBaseCalculator::execute_timer_, AMBSBaseCalculator::executeCB(), and AMBSBaseCalculator::nh_.
Referenced by CompFloatParam::init(), DiffFloatTemporal::init(), DiffPoseTemporal::init(), and Stopwatch::init().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_base_calculator/ambs_base_calculator.hpp