Automated Modular Benchmarking System: Test1Braking
Test1Braking
Test 1 braking starts a robot and stops after it reaches max vel or times out.
#include "test1_braking.h"
Public Member Functions
Test1Braking ()
Test1Braking (ros::NodeHandle nh, std::string node_name)
~Test1Braking () override
void executeCB (const ros::TimerEvent &event) override
Main runner logic, called by the timer. Overrides AMBSBaseRunner::executeCB()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseRunner
AMBSBaseRunner ()
AMBSBaseRunner (ros::NodeHandle nh, std::string node_name)
virtual ~AMBSBaseRunner ()
Private Attributes
std::vector< std::string > extended_inputs_ {ROBOT_IS_STATIONARY_, ROBOT_HAS_MAX_VEL_}
std::vector< std::string > extended_outputs_
const std::string PARAM_ACCELERATION_ = "acceleration_timeout"
double param_acceleration_
const std::string PARAM_DECCELERATION_ = "decceleration_timeout"
double param_decceleration_
const std::string PARAM_STABILIZATION_ = "stabilization_timeout"
double param_stabilization_
const std::string PARAM_VERIFICATION_ = "verification_timeout"
double param_verification_
const std::string ROBOT_HAS_MAX_VEL_ = "robot_has_max_vel"
const std::string ROBOT_IS_STATIONARY_ = "robot_is_stationary"
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseRunner
template<typename T >
T getResolvedParam (std::string param_name)
Gets a specified parameter by resolving to the ambs/runners namespace.
bool initialiseBaseRunner (ros::NodeHandle nh, std::string node_name, std::vector< std::string > extended_bool_inputs, std::vector< std::string > extended_bool_outputs)
Actual initialisation function.
void startRobot ()
void startRunner ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
void stopRobot ()
void testCompleted ()
Publish test results.
void testFailed ()
Publish test results.
void testSucceeded ()
Publish test results.
std::string timedLoopFallbackOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a true message, or if timer expires.
std::string timedLoopSequenceOnPorts (std::vector< std::string > *ports, double time, double rate)
Returns the first port in list that has a false message, or if timer expires.
ambs_msgs::BoolStamped waitForReset ()
Wait for TRUE on the RESET port.
ambs_msgs::BoolStamped waitForStart ()
Wait for TRUE on the START port.
Protected Attributes inherited from AMBSBaseRunner
std::string log_folder_path_
std::string log_path_
ros::NodeHandle nh_
std::string node_name_
const std::string PARAM_LOG_FOLDER_ = "/ambs/log_folder"
const std::string PARAM_LOG_ROOT_ = "/ambs/log_folder_root"
const std::string PARAM_ROBOT_NAME_ = "/ambs/robot_name"
const std::string RESET_TEST_ = "in_reset_test"
const std::string ROSBAG_BEGAN_ = "in_rosbag_began"
AMBSBooleanInterface signal_interface_
const std::string START_ROBOT_ = "out_start_robot"
const std::string START_TEST_ = "in_start_test"
const std::string STOP_ROBOT_ = "out_stop_robot"
const std::string TEST_COMPLETED_ = "out_test_completed"
const std::string TEST_FAILED_ = "out_test_failed"
const std::string TEST_SUCCEEDED_ = "out_test_succeeded"
Detailed Description
Test 1 braking starts a robot and stops after it reaches max vel or times out.
Constructor & Destructor Documentation
Test1Braking() [1/2]
Test1Braking () inline
{}
~Test1Braking()
~Test1Braking () inline override
{}
Test1Braking() [2/2]
Test1Braking (ros::NodeHandle nh, std::string node_name) inline
                                                     :
     ambs_base::AMBSBaseRunner(nh, node_name)
  {}
Member Function Documentation
executeCB()
void executeCB (const ros::TimerEvent & event) override virtual
Main runner logic, called by the timer. Overrides AMBSBaseRunner::executeCB()
Parameters
event Not used
Wait for start & rosbagger ready, then sleep to let robot initial jitter settle
Wait some time to let robot reach max vel. If timeout, test fail.
Wait some time and check again to see if robot maintained max vel
If so, then stop it
Implements AMBSBaseRunner.
{
  (void) event;
  std::string result;
  waitForStart();
  startRobot();
  ros::Duration(param_stabilization_).sleep();
  ROS_INFO_STREAM(node_name_ << ": Waiting " << param_acceleration_ <<"s for tobot to reach max vel");
  result = timedLoopFallbackOnPorts(new std::vector<std::string>{ROBOT_HAS_MAX_VEL_}, param_acceleration_);
  if (result == "")
  {
    ROS_WARN_STREAM(node_name_ << ": Robot did not reach max vel in expected time, ending test in failure!!");
    testFailed();
    stopRobot();
    waitForReset();
    return;
  }
  ROS_INFO_STREAM(node_name_ << ": Robot hit max vel, waiting " << param_acceleration_ <<"s to recheck");
  ros::Duration(param_verification_).sleep();
  if (signal_interface_.getPortMsg(ROBOT_HAS_MAX_VEL_).data)
  {
    ROS_INFO_STREAM(node_name_ << ": Robot maintained max vel, stopping it");
    stopRobot();
    // If it actually stops in a limited time, success, else failure
    result = timedLoopFallbackOnPorts(new std::vector<std::string>{ROBOT_IS_STATIONARY_}, param_decceleration_);
    if (result == ROBOT_IS_STATIONARY_)
    {
      ROS_WARN_STREAM(node_name_ << ": Robot has stopped, ending test in success!!");
      testSucceeded();
    }
    else
    {
      ROS_WARN_STREAM(node_name_ << ": Robot did not stop in " << param_decceleration_ <<"s, ending test in failure!!");
      testFailed();
    }
  }
  else
  {
    ROS_WARN_STREAM(node_name_ << ": Robot did not maintain max_vel, ending test in failure!!");
    testFailed();
  }
  waitForReset();
  return;
}
References AMBSTemplatedInterface< T >::getPortMsg(), AMBSBaseRunner::node_name_, Test1Braking::param_acceleration_, Test1Braking::param_decceleration_, Test1Braking::param_stabilization_, Test1Braking::param_verification_, Test1Braking::ROBOT_HAS_MAX_VEL_, Test1Braking::ROBOT_IS_STATIONARY_, AMBSBaseRunner::signal_interface_, AMBSBaseRunner::startRobot(), AMBSBaseRunner::stopRobot(), AMBSBaseRunner::testFailed(), AMBSBaseRunner::testSucceeded(), AMBSBaseRunner::timedLoopFallbackOnPorts(), AMBSBaseRunner::waitForReset(), and AMBSBaseRunner::waitForStart().
init()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseRunner::startRunner() spawns a timer which executes executeCB()
{
  ROS_INFO_STREAM(node_name_ << ": Init class");
  initialiseBaseRunner(nh_, node_name_, extended_inputs_, extended_outputs_);
  param_stabilization_ = getResolvedParam<double>(PARAM_STABILIZATION_);
  param_acceleration_ = getResolvedParam<double>(PARAM_ACCELERATION_);
  param_verification_ = getResolvedParam<double>(PARAM_VERIFICATION_);
  param_decceleration_ = getResolvedParam<double>(PARAM_DECCELERATION_);
  startRunner();
}
References Test1Braking::extended_inputs_, Test1Braking::extended_outputs_, AMBSBaseRunner::initialiseBaseRunner(), AMBSBaseRunner::nh_, AMBSBaseRunner::node_name_, Test1Braking::PARAM_ACCELERATION_, Test1Braking::param_acceleration_, Test1Braking::PARAM_DECCELERATION_, Test1Braking::param_decceleration_, Test1Braking::PARAM_STABILIZATION_, Test1Braking::param_stabilization_, Test1Braking::PARAM_VERIFICATION_, Test1Braking::param_verification_, and AMBSBaseRunner::startRunner().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_runners/test1_braking.h