Automated Modular Benchmarking System: CompFloatParam
CompFloatParam
Compare float from topic vs a param and output true when nearly equal.
#include "float_param_comparator.h"
Public Member Functions
CompFloatParam ()
CompFloatParam (ros::NodeHandle nh, std::string node_name)
~CompFloatParam ()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
Public Member Functions inherited from AMBSBaseCalculator
AMBSBaseCalculator ()
AMBSBaseCalculator (ros::NodeHandle nh, std::string node_name)
Constructor.
virtual ~AMBSBaseCalculator ()
Private Member Functions
void executeCB (const ros::TimerEvent &event) override
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Private Attributes
ambs_base::AMBSTemplatedInterface< std_msgs::Float64 > float_interface_
const std::string IN_FLOAT_ = "/in_float"
Input float topic.
ros::NodeHandle nh_
const std::string PARAM_ = "param"
std_msgs::Float64 result_msg_
const std::string TOLERANCE_ = "tolerance"
Additional Inherited Members
Protected Member Functions inherited from AMBSBaseCalculator
template<typename T >
T getResolvedParam (std::string param_name)
Gets a specified parameter by resolving to the ambs/calculators namespace.
void startCalculator ()
Starts the timer thread. MUST BE EXPLICITLY CALLED.
Protected Attributes inherited from AMBSBaseCalculator
AMBSDefaultCalculatorInterface default_control_
ros::NodeHandle nh_
std::string node_name_
Detailed Description
Compare float from topic vs a param and output true when nearly equal.
Has standard control intetrface, and a float interface with one input and one output port, and two rosparams
Constructor & Destructor Documentation
CompFloatParam() [1/2]
CompFloatParam () inline
{}
~CompFloatParam()
~CompFloatParam () inline
{}
CompFloatParam() [2/2]
CompFloatParam (ros::NodeHandle nh, std::string node_name) inline
                                                       :
    ambs_base::AMBSBaseCalculator(nh, node_name),
    nh_(nh)
  {}
Member Function Documentation
executeCB()
void executeCB (const ros::TimerEvent & event) override private virtual
Main calculator logic, called by the timer. Overrides AMBSBaseCalculator::executeCB()
Parameters
event Not used
Implements AMBSBaseCalculator.
{
  (void) event;
  default_control_.waitForStart();
  float param = getResolvedParam<float>(PARAM_);
  float tolerance = getResolvedParam<float>(TOLERANCE_);
  bool is_published = false;
  ros::Rate loop(10);
  while (ros::ok())
  {
    ros::spinOnce();
    loop.sleep();
     if (default_control_.getStopMsg().data)
     {
       ROS_INFO_STREAM(node_name_ << ": Got stop");
       break;
     }
     if (!float_interface_.isPortValid(IN_FLOAT_))
     {
       continue;
     }
     float float_val = float_interface_.getPortMsg(IN_FLOAT_).data;
     if (std::abs(float_val - param) <= tolerance)
     {
       if (!is_published)
       {
         ROS_INFO_STREAM(node_name_ << ": Comparison TRUE");
         default_control_.publishDone();
         is_published = true;
       }
     }
     else if (is_published)
     {
       ROS_INFO_STREAM(node_name_ << ": Comparison FALSE");
       is_published = false;
     }
  }
  default_control_.waitForReset();
  float_interface_.resetAllPorts();
  ROS_INFO_STREAM(node_name_ << ": Restarting calculator");
  ROS_INFO(" ");
  ROS_INFO("-----------------------------------------------------------");
  ROS_INFO(" ");
}
References AMBSBaseCalculator::default_control_, CompFloatParam::float_interface_, AMBSDefaultCalculatorInterface::getStopMsg(), CompFloatParam::IN_FLOAT_, AMBSBaseCalculator::node_name_, CompFloatParam::PARAM_, AMBSDefaultCalculatorInterface::publishDone(), CompFloatParam::TOLERANCE_, AMBSDefaultCalculatorInterface::waitForReset(), and AMBSDefaultCalculatorInterface::waitForStart().
init()
void init ()
init function will be called by nodelet, so it is not called anywhere from within class
AMBSBaseCalculator::startCalculator() spawns a timer which executes executeCB()
{
  ROS_INFO_STREAM(node_name_ <<": Init class");
  std::vector<std::string> float_inputs{IN_FLOAT_};
  std::vector<std::string> float_outputs;
  float_interface_.init(float_inputs, float_outputs, nh_, node_name_);
  startCalculator();
}
References CompFloatParam::float_interface_, CompFloatParam::IN_FLOAT_, CompFloatParam::nh_, AMBSBaseCalculator::node_name_, and AMBSBaseCalculator::startCalculator().
The documentation for this class was generated from the following file:
ambs_components/include/ambs_calculators/comparators/float_param_comparator.h