Automated Modular Benchmarking System: ambs_core/src/test_base.cpp File Reference
test_base.cpp File Reference
#include <map>
#include <string>
#include <vector>
#include "ambs_base_interface/ambs_base_interface.hpp"
#include "ambs_base_calculator/ambs_default_calculator_interface.hpp"
#include "std_msgs/Float64.h"
#include "ambs_msgs/BoolStamped.h"
#include "ambs_base_calculator/ambs_base_calculator.hpp"
#include "ambs_base_runner/ambs_base_runner.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
{
  ros::init(argc, argv, "test_base");
  ros::NodeHandle nh;
  std::vector<std::string> float_inputs;
  float_inputs.push_back("/in_float");
  std::vector<std::string> float_outputs;
  float_outputs.push_back("/out_float");
  ambs_base::AMBSDefaultCalculatorInterface standard_control;
  standard_control.initDefaultInterface(nh, "test_base");
  ambs_base::AMBSTemplatedInterface<std_msgs::Float64> float_interface(float_inputs, float_outputs, nh, "test_base");
  ros::Rate loop(2);
  int i = 0;
  while (ros::ok())
  {
    if (i % 10 == 0)
    {
      ROS_WARN_STREAM("Manually setting output port");
      std_msgs::Float64 msg;
      msg.data = 34.56;
      float_interface.setPortMsg("/out_float", msg);
    }
    if (i++ % 20 == 0)
    {
      ROS_WARN_STREAM(std::to_string(i) << ": Resetting all float ports");
      float_interface.resetAllPorts();
    }
    float_interface.printPorts();
    ros::spinOnce();
    loop.sleep();
  }
}
References AMBSDefaultCalculatorInterface::initDefaultInterface(), AMBSTemplatedInterface< T >::printPorts(), AMBSTemplatedInterface< T >::resetAllPorts(), and AMBSTemplatedInterface< T >::setPortMsg().