Automated Modular Benchmarking System: AMBSStandardControlInterface
AMBSStandardControlInterface
A bool specialization of the AMBSTemplatedInterface base class.
#include "ambs_standard_control_interface.hpp"
Public Member Functions
AMBSStandardControlInterface ()
ambs_msgs::BoolStamped contructNewBoolStamped (bool data)
Create a new BoolStamped type message.
ambs_msgs::BoolStamped getStartMsg ()
Get the message received by the START_ port.
ambs_msgs::BoolStamped getStopMsg ()
Get the message received by the STOP_ port.
void init (ros::NodeHandle nh, std::string node_name)
Initialisation decoupled from constructor for convenince.
void printPorts ()
Print internal buffer values of all ports.
void publishDone ()
Publish TRUE on the DONE port.
void resetAllPorts ()
Reset internal buffers of all ports.
void resetPort (std::string port)
Reset internal buffer of a specific port.
ambs_msgs::BoolStamped waitForReset ()
Wait for TRUE on the RESET port.
ambs_msgs::BoolStamped waitForStart ()
Wait for TRUE on the START port.
ambs_msgs::BoolStamped waitForStop ()
Wait for TRUE on the STOP port.
Public Attributes
AMBSTemplatedInterface< ambs_msgs::BoolStamped > control_interface_
Private Member Functions
ambs_msgs::BoolStamped waitForTrueOnPort (std::string port)
Wait for TRUE on a port.
Private Attributes
const std::vector< std::string > default_inputs_ {START_, STOP_, RESET_}
const std::vector< std::string > default_outputs_ {DONE_}
const std::string DONE_ = "/out_done"
The DONE port.
ros::NodeHandle nh_
std::string node_name_
const std::string RESET_ = "/in_reset"
The RESET port.
const std::string START_ = "/in_start"
The START port.
const std::string STOP_ = "/in_stop"
The STOP port.
const double wait_loop_rate = 100
Detailed Description
A bool specialization of the AMBSTemplatedInterface base class.
Useful because all components should have a standard boolean control interface such as start, stop, reset & done
Constructor & Destructor Documentation
AMBSStandardControlInterface()
AMBSStandardControlInterface () inline
{}
Member Function Documentation
contructNewBoolStamped()
ambs_msgs::BoolStamped contructNewBoolStamped (bool data) inline
Create a new BoolStamped type message.
Parameters
[in] data The data to be held by the new msg
Returns
msg The message to be returned
{
  ambs_msgs::BoolStamped msg;
  msg.data  = data;
  msg.header = std_msgs::Header();
  msg.header.stamp = ros::Time::now();
  return msg;
}
Referenced by AMBSStandardControlInterface::publishDone().
getStartMsg()
ambs_msgs::BoolStamped getStartMsg () inline
Get the message received by the START_ port.
Returns
msg The message
{
  return control_interface_.getPortMsg(START_);
}
References AMBSStandardControlInterface::control_interface_, and AMBSStandardControlInterface::START_.
getStopMsg()
ambs_msgs::BoolStamped getStopMsg () inline
Get the message received by the STOP_ port.
Returns
msg The message
{
  return control_interface_.getPortMsg(STOP_);
}
References AMBSStandardControlInterface::control_interface_, and AMBSStandardControlInterface::STOP_.
Referenced by CompFloatParam::executeCB().
init()
void init (ros::NodeHandle nh, std::string node_name) inline
Initialisation decoupled from constructor for convenince.
{
  nh_ = nh;
  node_name_ = node_name;
  control_interface_.init(default_inputs_,default_outputs_,nh, node_name);
}
References AMBSStandardControlInterface::control_interface_, AMBSStandardControlInterface::default_inputs_, AMBSStandardControlInterface::default_outputs_, AMBSStandardControlInterface::nh_, and AMBSStandardControlInterface::node_name_.
Referenced by AMBSBaseCalculator::initialiseCalc(), AMBSBaseRunner::initialiseRunner(), and main().
printPorts()
void printPorts () inline
Print internal buffer values of all ports.
Used mainly for debugging
{
  ROS_INFO_STREAM("Start : " << std::to_string(control_interface_.getPortMsg(START_).data)
                  << " Stop : " << std::to_string(control_interface_.getPortMsg(STOP_).data)
                  << " Reset : " << std::to_string(control_interface_.getPortMsg(RESET_).data)
                  << " Done : " << std::to_string(control_interface_.getPortMsg(DONE_).data));
}
References AMBSStandardControlInterface::control_interface_, AMBSStandardControlInterface::DONE_, AMBSStandardControlInterface::RESET_, AMBSStandardControlInterface::START_, and AMBSStandardControlInterface::STOP_.
publishDone()
void publishDone () inline
Publish TRUE on the DONE port.
{
  control_interface_.publishMsgOnPort(DONE_, contructNewBoolStamped(true));
}
References AMBSStandardControlInterface::control_interface_, AMBSStandardControlInterface::contructNewBoolStamped(), and AMBSStandardControlInterface::DONE_.
Referenced by Stopwatch::executeCB(), CompFloatParam::executeCB(), and DiffFloatTemporal::executeCB().
resetAllPorts()
void resetAllPorts () inline
Reset internal buffers of all ports.
{
  control_interface_.resetAllPorts();
}
References AMBSStandardControlInterface::control_interface_.
Referenced by AMBSStandardControlInterface::waitForReset().
resetPort()
void resetPort (std::string port) inline
Reset internal buffer of a specific port.
Parameters
port The port to reset
{
  control_interface_.resetPort(port);
}
References AMBSStandardControlInterface::control_interface_.
Referenced by AMBSStandardControlInterface::waitForTrueOnPort().
waitForReset()
ambs_msgs::BoolStamped waitForReset () inline
Wait for TRUE on the RESET port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ <<  ": Wait for Reset");
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(RESET_);
  ROS_INFO_STREAM(node_name_ << ": Got Reset");
  return msg;
  resetAllPorts();
}
References AMBSStandardControlInterface::node_name_, AMBSStandardControlInterface::RESET_, AMBSStandardControlInterface::resetAllPorts(), and AMBSStandardControlInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), CompFloatParam::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForStart()
ambs_msgs::BoolStamped waitForStart () inline
Wait for TRUE on the START port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ << ": Wait for Start");
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(START_);
  ROS_INFO_STREAM(node_name_ << ": Got Start");
  return msg;
}
References AMBSStandardControlInterface::node_name_, AMBSStandardControlInterface::START_, and AMBSStandardControlInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), CompFloatParam::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForStop()
ambs_msgs::BoolStamped waitForStop () inline
Wait for TRUE on the STOP port.
Returns
The msg that set TRUE
{
  ROS_INFO_STREAM(node_name_ <<  ": Wait for Stop");
  ambs_msgs::BoolStamped msg = waitForTrueOnPort(STOP_);
  ROS_INFO_STREAM(node_name_ << ": Got Stop");
  return msg;
}
References AMBSStandardControlInterface::node_name_, AMBSStandardControlInterface::STOP_, and AMBSStandardControlInterface::waitForTrueOnPort().
Referenced by Stopwatch::executeCB(), DiffFloatTemporal::executeCB(), and DiffPoseTemporal::executeCB().
waitForTrueOnPort()
ambs_msgs::BoolStamped waitForTrueOnPort (std::string port) inline private
Wait for TRUE on a port.
Parameters
port The port to wait on
Returns
The msg that set TRUE
{
  ambs_msgs::BoolStamped msg;
  ros::Rate loop(wait_loop_rate);
  while(ros::ok())
  {
    loop.sleep();
    ros::spinOnce();
    msg = control_interface_.getPortMsg(port);
    if(msg.data)
    {
      break;
    }
  }
  resetPort(port);
  return msg;
}
References AMBSStandardControlInterface::control_interface_, AMBSStandardControlInterface::resetPort(), and AMBSStandardControlInterface::wait_loop_rate.
Referenced by AMBSStandardControlInterface::waitForReset(), AMBSStandardControlInterface::waitForStart(), and AMBSStandardControlInterface::waitForStop().
The documentation for this class was generated from the following file:
ambs_core/include/ambs_base_interface/ambs_standard_control_interface.hpp